name: 'tuva_chronic_conditions'
version: '0.0.1'
config-version: 2

profile: 'default'

vars:
    condition: |
        {% if var('tuva_chronic_conditions_condition_override',none) is not none %}{{var('tuva_chronic_conditions_condition_override')}}
        {%- elif var('core_condition_override',none) is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {% endif %}



# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

