name: 'tuva_chronic_conditions_input'
version: '1.0.0'
config-version: 2

profile: 'default'

vars:
  tuva_chronic_conditions_condition_override: "{{ ref('condition')}}"

dispatch:
  - macro_namespace: dbt
    search_order: [ 'tuva_chronic_conditions', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["documents"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
